---

- name: fio write benchmark on tikv_data_dir disk
  shell: "cd {{ fio_deploy_dir }} && ./fio -filename=fio_write_test.txt -direct=0 -iodepth 1 -thread -rw=write -ioengine=psync -bs=16k -size={{ benchmark_size }} -numjobs=6 -runtime=60 -group_reporting -name='fio write test' -group_reporting --output-format=json --output=fio_write_result.json"
  register: fio_write

- name: clean fio write benchmark temporary file
  file:
    path: "{{ fio_deploy_dir }}/fio_write_test.txt"
    state: absent

- name: get fio write bandwidth
  shell: "python parse_fio_output.py --target='fio_write_result.json' --write-bw"
  register: disk_write_iops
  args:
    chdir: "{{ fio_deploy_dir }}/"

- name: get fio read bandwidth
  shell: "python parse_fio_output.py --target='fio_write_result.json' --read-bw"
  register: disk_read_iops
  args:
    chdir: "{{ fio_deploy_dir }}/"

- name: fio randread benchmark command
  debug:
    msg: "fio randread benchmark command: {{ fio_randread.cmd }}."
  run_once: true
